// seedSanDiegoZones.js
// Data sourced directly from San Diego Municipal Code Ch.13 Art.1 Div.4 (3-2026)
// Tables 131-04D (RS), 131-04E (RX), 131-04F (RT), 131-04G (RM)

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://clskmcueoaoslacskjzj.supabase.co';
const SUPABASE_KEY = 'sb_publishable_PKi4TSl3088C_1zT0boUdg_t2Mf4Jo5';
const SOURCE_URL   = 'https://docs.sandiego.gov/municode/MuniCodeChapter13/Ch13Art01Division04.pdf';
const EFF_DATE     = '2025-04-24';

const ZONES = [
  // ── RS Zones (Urbanized) — Table 131-04D ──────────────────────────────────
  { zone:'RS-1-1', standards:{ min_lot_area:{value:'40000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'25',unit:'ft',notes:'cul-de-sac may reduce to 6 ft min'}, side_setback:{value:'10',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'25',unit:'ft',notes:''}, max_height:{value:'24/30',unit:'ft',notes:'24 ft flat roof / 30 ft sloped'}, max_far:{value:'0.45',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-2', standards:{ min_lot_area:{value:'20000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'25',unit:'ft',notes:''}, side_setback:{value:'8',unit:'ft',notes:''}, street_side_setback:{value:'8',unit:'ft',notes:''}, rear_setback:{value:'25',unit:'ft',notes:''}, max_height:{value:'24/30',unit:'ft',notes:''}, max_far:{value:null,unit:'',notes:'Varies by lot size per Table 131-04J'} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-3', standards:{ min_lot_area:{value:'15000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'20',unit:'ft',notes:''}, side_setback:{value:'7',unit:'ft',notes:''}, street_side_setback:{value:'7',unit:'ft',notes:''}, rear_setback:{value:'20',unit:'ft',notes:''}, max_height:{value:'24/30',unit:'ft',notes:''}, max_far:{value:null,unit:'',notes:'Varies by lot size'} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-4', standards:{ min_lot_area:{value:'10000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'20',unit:'ft',notes:''}, side_setback:{value:'6',unit:'ft',notes:''}, street_side_setback:{value:'6',unit:'ft',notes:''}, rear_setback:{value:'20',unit:'ft',notes:''}, max_height:{value:'24/30',unit:'ft',notes:''}, max_far:{value:null,unit:'',notes:'Varies by lot size'} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-5', standards:{ min_lot_area:{value:'8000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'20',unit:'ft',notes:''}, side_setback:{value:'5',unit:'ft',notes:''}, street_side_setback:{value:'6',unit:'ft',notes:''}, rear_setback:{value:'20',unit:'ft',notes:''}, max_height:{value:'24/30',unit:'ft',notes:''}, max_far:{value:null,unit:'',notes:'Varies by lot size'} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-6', standards:{ min_lot_area:{value:'6000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'15',unit:'ft',notes:''}, side_setback:{value:'5',unit:'ft',notes:''}, street_side_setback:{value:'6',unit:'ft',notes:''}, rear_setback:{value:'15',unit:'ft',notes:''}, max_height:{value:'24/30',unit:'ft',notes:''}, max_far:{value:null,unit:'',notes:'Varies by lot size'} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-7', standards:{ min_lot_area:{value:'5000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'15',unit:'ft',notes:''}, side_setback:{value:'4',unit:'ft',notes:''}, street_side_setback:{value:'5',unit:'ft',notes:''}, rear_setback:{value:'13',unit:'ft',notes:''}, max_height:{value:'24/30',unit:'ft',notes:''}, max_far:{value:null,unit:'',notes:'Varies by lot size'} }, citation:'§131.0431 / Table 131-04D' },
  // RS Zones (Planned Urbanized / Prop A)
  { zone:'RS-1-8',  standards:{ min_lot_area:{value:'40000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'25',unit:'ft',notes:''}, side_setback:{value:'10',unit:'ft',notes:''}, street_side_setback:{value:'20',unit:'ft',notes:''}, rear_setback:{value:'10',unit:'ft',notes:'alley: may reduce to 4 ft'}, max_height:{value:'35',unit:'ft',notes:''}, max_far:{value:'0.45',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-9',  standards:{ min_lot_area:{value:'20000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:''}, front_setback:{value:'25',unit:'ft',notes:''}, side_setback:{value:'8',unit:'ft',notes:''}, street_side_setback:{value:'15',unit:'ft',notes:''}, rear_setback:{value:'10',unit:'ft',notes:''}, max_height:{value:'35',unit:'ft',notes:''}, max_far:{value:'0.60',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-10', standards:{ min_lot_area:{value:'15000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:''}, front_setback:{value:'25',unit:'ft',notes:''}, side_setback:{value:'7',unit:'ft',notes:''}, street_side_setback:{value:'15',unit:'ft',notes:''}, rear_setback:{value:'10',unit:'ft',notes:''}, max_height:{value:'35',unit:'ft',notes:''}, max_far:{value:'0.60',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-11', standards:{ min_lot_area:{value:'10000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:''}, front_setback:{value:'20',unit:'ft',notes:''}, side_setback:{value:'6',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'10',unit:'ft',notes:''}, max_height:{value:'35',unit:'ft',notes:''}, max_far:{value:'0.60',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-12', standards:{ min_lot_area:{value:'8000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:''}, front_setback:{value:'15',unit:'ft',notes:''}, side_setback:{value:'5',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'10',unit:'ft',notes:''}, max_height:{value:'35',unit:'ft',notes:''}, max_far:{value:'0.60',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-13', standards:{ min_lot_area:{value:'6000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:''}, front_setback:{value:'15',unit:'ft',notes:''}, side_setback:{value:'5',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'10',unit:'ft',notes:''}, max_height:{value:'35',unit:'ft',notes:''}, max_far:{value:'0.60',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04D' },
  { zone:'RS-1-14', standards:{ min_lot_area:{value:'5000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:''}, front_setback:{value:'15',unit:'ft',notes:''}, side_setback:{value:'4',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'10',unit:'ft',notes:''}, max_height:{value:'35',unit:'ft',notes:''}, max_far:{value:'0.60',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04D' },
  // ── RX Zones — Table 131-04E ──────────────────────────────────────────────
  { zone:'RX-1-1', standards:{ min_lot_area:{value:'4000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'15',unit:'ft',notes:''}, side_setback:{value:'3/0',unit:'ft',notes:'3 ft detached; 0 ft attached one side'}, street_side_setback:{value:'3',unit:'ft',notes:''}, rear_setback:{value:'10',unit:'ft',notes:'4 ft if alley access'}, max_height:{value:'30',unit:'ft',notes:''}, max_far:{value:'0.70',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04E' },
  { zone:'RX-1-2', standards:{ min_lot_area:{value:'3000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'15',unit:'ft',notes:''}, side_setback:{value:'3/0',unit:'ft',notes:'3 ft detached; 0 ft attached one side'}, street_side_setback:{value:'3',unit:'ft',notes:''}, rear_setback:{value:'10',unit:'ft',notes:'4 ft if alley access'}, max_height:{value:'30',unit:'ft',notes:''}, max_far:{value:'0.80',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04E' },
  // ── RT Zones — Table 131-04F ──────────────────────────────────────────────
  { zone:'RT-1-1', standards:{ min_lot_area:{value:'3500',unit:'sf',notes:''}, density:{value:null,unit:'',notes:'1 DU per lot'}, front_setback:{value:'5/15',unit:'ft',notes:'min 5 ft, max 15 ft; portion of facade must be within 1 ft of setback line'}, side_setback:{value:'0',unit:'ft',notes:'zero side setback; 3 ft if adjacent non-RT zone'}, street_side_setback:{value:'5',unit:'ft',notes:''}, rear_setback:{value:'3',unit:'ft',notes:''}, max_height:{value:'21/25',unit:'ft',notes:'slab 21 ft / raised floor 25 ft; 3-story: 31/35 ft'}, max_far:{value:'0.85',unit:'',notes:'1-2 story; 3-story: 1.20'} }, citation:'§131.0431 / Table 131-04F' },
  { zone:'RT-1-2', standards:{ min_lot_area:{value:'3000',unit:'sf',notes:''}, density:{value:null,unit:'',notes:''}, front_setback:{value:'5/15',unit:'ft',notes:'min 5, max 15'}, side_setback:{value:'0',unit:'ft',notes:''}, street_side_setback:{value:'5',unit:'ft',notes:''}, rear_setback:{value:'3',unit:'ft',notes:''}, max_height:{value:'21/25',unit:'ft',notes:'3-story: 31/35 ft'}, max_far:{value:'0.95',unit:'',notes:'1-2 story; 3-story: 1.30'} }, citation:'§131.0431 / Table 131-04F' },
  { zone:'RT-1-3', standards:{ min_lot_area:{value:'2500',unit:'sf',notes:''}, density:{value:null,unit:'',notes:''}, front_setback:{value:'5/15',unit:'ft',notes:''}, side_setback:{value:'0',unit:'ft',notes:''}, street_side_setback:{value:'5',unit:'ft',notes:''}, rear_setback:{value:'3',unit:'ft',notes:''}, max_height:{value:'21/25',unit:'ft',notes:'3-story: 31/35 ft'}, max_far:{value:'1.00',unit:'',notes:'3-story: 1.40'} }, citation:'§131.0431 / Table 131-04F' },
  { zone:'RT-1-4', standards:{ min_lot_area:{value:'2200',unit:'sf',notes:''}, density:{value:null,unit:'',notes:''}, front_setback:{value:'5/15',unit:'ft',notes:''}, side_setback:{value:'0',unit:'ft',notes:''}, street_side_setback:{value:'5',unit:'ft',notes:''}, rear_setback:{value:'3',unit:'ft',notes:''}, max_height:{value:'21/25',unit:'ft',notes:'3-story: 31/35 ft'}, max_far:{value:'1.10',unit:'',notes:'3-story: 1.50'} }, citation:'§131.0431 / Table 131-04F' },
  { zone:'RT-1-5', standards:{ min_lot_area:{value:'1600',unit:'sf',notes:'lot width min 18 ft'}, density:{value:null,unit:'',notes:''}, front_setback:{value:'5/10',unit:'ft',notes:'min 5, max 10'}, side_setback:{value:'0',unit:'ft',notes:''}, street_side_setback:{value:'5',unit:'ft',notes:''}, rear_setback:{value:'3',unit:'ft',notes:''}, max_height:{value:'21/25',unit:'ft',notes:'3-story: 31/35 ft'}, max_far:{value:'1.20',unit:'',notes:'3-story: 1.60'} }, citation:'§131.0431 / Table 131-04F' },
  // ── RM Zones — Table 131-04G ──────────────────────────────────────────────
  // RM-1-1 already in DB (version 2) — included here so upsert refreshes it
  { zone:'RM-1-1', standards:{ min_lot_area:{value:'6000',unit:'sf',notes:'density = 1 DU per 3,000 sf lot area'}, density:{value:'1 DU / 3000 sf',unit:'',notes:''}, front_setback:{value:'15/20',unit:'ft',notes:'min 15 ft; standard 20 ft'}, side_setback:{value:'5/8',unit:'ft',notes:'min 5 ft; standard 8 ft or 10% lot width'}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'15',unit:'ft',notes:'alley: half width may count, min 5 ft on premises'}, max_height:{value:'30',unit:'ft',notes:''}, max_far:{value:'0.75',unit:'',notes:'1-2 DU; 3-7 DU: 1.0; 8+ DU: 1.25'} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-1-2', standards:{ min_lot_area:{value:'6000',unit:'sf',notes:''}, density:{value:'1 DU / 2500 sf',unit:'',notes:''}, front_setback:{value:'15/20',unit:'ft',notes:'min 15; standard 20'}, side_setback:{value:'5/8',unit:'ft',notes:'min 5; standard 8 ft or 10% lot width'}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'15',unit:'ft',notes:''}, max_height:{value:'30',unit:'ft',notes:''}, max_far:{value:'0.90',unit:'',notes:'1-2 DU; 3-7 DU: 1.0; 8+ DU: 1.25'} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-1-3', standards:{ min_lot_area:{value:'6000',unit:'sf',notes:''}, density:{value:'1 DU / 2000 sf',unit:'',notes:''}, front_setback:{value:'15/20',unit:'ft',notes:''}, side_setback:{value:'5/8',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'15',unit:'ft',notes:''}, max_height:{value:'30',unit:'ft',notes:''}, max_far:{value:'1.05',unit:'',notes:'1-2 DU; 3-7 DU: 1.05; 8+ DU: 1.25'} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-2-4', standards:{ min_lot_area:{value:'6000',unit:'sf',notes:''}, density:{value:'1 DU / 1750 sf',unit:'',notes:''}, front_setback:{value:'15/20',unit:'ft',notes:''}, side_setback:{value:'5',unit:'ft',notes:'min; or 10% lot width whichever greater'}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'15',unit:'ft',notes:''}, max_height:{value:'40',unit:'ft',notes:''}, max_far:{value:'1.20',unit:'',notes:'1-2 DU; 3-7 DU: 1.20; 8+ DU: 1.25'} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-2-5', standards:{ min_lot_area:{value:'6000',unit:'sf',notes:''}, density:{value:'1 DU / 1500 sf',unit:'',notes:''}, front_setback:{value:'15/20',unit:'ft',notes:''}, side_setback:{value:'5',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'15',unit:'ft',notes:''}, max_height:{value:'40',unit:'ft',notes:''}, max_far:{value:'1.35',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-2-6', standards:{ min_lot_area:{value:'6000',unit:'sf',notes:''}, density:{value:'1 DU / 1250 sf',unit:'',notes:''}, front_setback:{value:'15/20',unit:'ft',notes:''}, side_setback:{value:'5',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'15',unit:'ft',notes:''}, max_height:{value:'40',unit:'ft',notes:''}, max_far:{value:'1.50',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-3-7', standards:{ min_lot_area:{value:'7000',unit:'sf',notes:''}, density:{value:'1 DU / 1000 sf',unit:'',notes:''}, front_setback:{value:'10/20',unit:'ft',notes:'min 10; standard 20'}, side_setback:{value:'5',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'5',unit:'ft',notes:''}, max_height:{value:'40',unit:'ft',notes:''}, max_far:{value:'1.80',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-3-8', standards:{ min_lot_area:{value:'7000',unit:'sf',notes:''}, density:{value:'1 DU / 800 sf',unit:'',notes:''}, front_setback:{value:'10/20',unit:'ft',notes:''}, side_setback:{value:'5',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'5',unit:'ft',notes:''}, max_height:{value:'50',unit:'ft',notes:''}, max_far:{value:'2.25',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-3-9', standards:{ min_lot_area:{value:'7000',unit:'sf',notes:''}, density:{value:'1 DU / 600 sf',unit:'',notes:''}, front_setback:{value:'10/20',unit:'ft',notes:''}, side_setback:{value:'5',unit:'ft',notes:''}, street_side_setback:{value:'10',unit:'ft',notes:''}, rear_setback:{value:'5',unit:'ft',notes:''}, max_height:{value:'60',unit:'ft',notes:''}, max_far:{value:'2.70',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-4-10', standards:{ min_lot_area:{value:'7000',unit:'sf',notes:''}, density:{value:'1 DU / 400 sf',unit:'',notes:''}, front_setback:{value:null,unit:'ft',notes:'Varies — see §131.0443(g): 15 ft on N and E elevations'}, side_setback:{value:null,unit:'ft',notes:'Varies per §131.0443(g)'}, street_side_setback:{value:null,unit:'ft',notes:''}, rear_setback:{value:null,unit:'ft',notes:''}, max_height:{value:null,unit:'ft',notes:'No base zone height limit'}, max_far:{value:'3.60',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-4-11', standards:{ min_lot_area:{value:'7000',unit:'sf',notes:''}, density:{value:'1 DU / 200 sf',unit:'',notes:''}, front_setback:{value:null,unit:'ft',notes:'Varies per §131.0443(g)'}, side_setback:{value:null,unit:'ft',notes:''}, street_side_setback:{value:null,unit:'ft',notes:''}, rear_setback:{value:null,unit:'ft',notes:''}, max_height:{value:null,unit:'ft',notes:'No base zone height limit'}, max_far:{value:'7.20',unit:'',notes:''} }, citation:'§131.0431 / Table 131-04G' },
  { zone:'RM-5-12', standards:{ min_lot_area:{value:'10000',unit:'sf',notes:''}, density:{value:'1 DU / 1000 sf',unit:'',notes:'La Jolla/Pacific Beach/Torrey Pines: 1 DU / 1500 sf'}, front_setback:{value:'15',unit:'ft',notes:'§131.0443(h)(1)'}, side_setback:{value:'4',unit:'ft',notes:'increases 3 ft per 12 ft height over 24 ft'}, street_side_setback:{value:'10',unit:'ft',notes:'varies by lot width per §131.0443(h)(3)'}, rear_setback:{value:'15',unit:'ft',notes:'increases 3 ft per 12 ft height over 24 ft'}, max_height:{value:null,unit:'ft',notes:'No base limit; coastal overlay: 30 ft'}, max_far:{value:'1.80',unit:'',notes:'increases with height per Table 131-04K'} }, citation:'§131.0431 / Table 131-04G' },
];

async function run() {
  const sb = createClient(SUPABASE_URL, SUPABASE_KEY);
  console.log(`Seeding ${ZONES.length} San Diego residential zones...`);
  let saved = 0, failed = 0;

  for (const z of ZONES) {
    const { error } = await sb.from('zoning_standards').upsert(
      { jurisdiction:'San Diego, CA', zone:z.zone, standards:z.standards, citation:z.citation, confidence:'high', missing:[], source_url:SOURCE_URL, source_effective_date:EFF_DATE, retrieved_at:new Date().toISOString() },
      { onConflict:'jurisdiction,zone' }
    );
    if (error) { console.error(`  ✗  ${z.zone}: ${error.message}`); failed++; }
    else { console.log(`  ✓  ${z.zone}`); saved++; }
  }
  console.log(`\nDone. ${saved} saved, ${failed} failed.`);
}

run();
